name: 'ad_reporting'
version: '1.4.0'

config-version: 2

require-dbt-version: [">=1.3.0", "<2.0.0"]

vars:
  ad_reporting:
    ad_reporting__account_passthrough_metrics: []
    ad_reporting__campaign_passthrough_metrics: []
    ad_reporting__ad_group_passthrough_metrics: []
    ad_reporting__ad_passthrough_metrics: []
    ad_reporting__keyword_passthrough_metrics: []
    ad_reporting__search_passthrough_metrics: []

    ad_reporting__amazon_ads_enabled: False 
    ad_reporting__apple_search_ads_enabled: False 
    ad_reporting__pinterest_ads_enabled: False 
    ad_reporting__microsoft_ads_enabled: False 
    ad_reporting__snapchat_ads_enabled: False 
    ad_reporting__tiktok_ads_enabled: False 
    ad_reporting__reddit_ads_enabled: False 

models:
  ad_reporting:
    +materialized: table 
    +schema: ad_reporting 
    intermediate:
      +materialized: ephemeral
      +schema: int_ad_reporting
